version: '2'
services:
  mariadb:
    image: bitnami/mariadb:10.6-debian-11
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
      - MARIADB_PASSWORD=mia?ng1Iew%u
      - MARIADB_ROOT_PASSWORD=eeKohk6ogh:a
    volumes:
      - 'mariadb_data:/bitnami/mariadb'

  moodle:
    build: 
      context: .
      dockerfile: moodle-build
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_DATABASE_PASSWORD=mia?ng1Iew%u
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=ohs6UNu0De#x
    volumes:
      - 'moodle_code:/var/www/moodle'
      - 'moodle_data:/var/www/moodledata'
    depends_on:
       - mariadb
    tty:
      true
volumes:
  mariadb_data:
    driver: local
  moodle_code:
    driver: local
  moodle_data:
    driver: local
